global:
      - targets: ['rabbitmq:15672']
    static_configs:
  - job_name: 'rabbitmq'

      - targets: ['redis:6379']
    static_configs:
  - job_name: 'redis'

        - 'host.docker.internal:20262' # Order Service
        - 'host.docker.internal:20261' # Customer Service
        - 'host.docker.internal:20260' # Account Service
        - 'host.docker.internal:8070'  # Gateway Server
        - 'host.docker.internal:8761'  # Eureka Server
        - 'host.docker.internal:8888'  # Config Server
      - targets:
    static_configs:
    metrics_path: '/actuator/prometheus'
  - job_name: 'spring-boot-microservices'

      - targets: ['localhost:9090']
    static_configs:
  - job_name: 'prometheus'
scrape_configs:

  evaluation_interval: 15s
  scrape_interval: 15s

