services:
  # deploy postgresSQL for microservice
  pg-itp-micro-db:
    image: postgres:17.5-bullseye
    container_name: pg-itp-micro-db
    environment:
      POSTGRES_USER: itpusr
      POSTGRES_PASSWORD: itp@168
      POSTGRES_DB: itp_micro_db
    ports:
      - "16851:5432"
    volumes:
      - ./init_scripts/pg_itp_micro_init.sql:/docker-entrypoint-initdb.d/pg_itp_micro_init.sql
      - pg-itp-micro-vol:/var/lib/postgresql/data
    networks:
      - itp-net

  # deploy postgresSQL for identity access management
  pg-itp-iam-db:
    image: postgres:17.5-bullseye
    container_name: pg-itp-iam-db
    environment:
      POSTGRES_USER: itpusr
      POSTGRES_PASSWORD: itp@168
      POSTGRES_DB: itp_iam_db    # <--- FIXED: Changed to unique name
    ports:
      - "16852:5432"
    volumes:
      - ./init_scripts/pg_itp_iam_init.sql:/docker-entrypoint-initdb.d/pg_itp_iam_init.sql
      - pg-itp-iam-vol:/var/lib/postgresql/data
    networks:
      - itp-net

#create docker volumes internally
volumes:
  pg-itp-iam-vol:
  pg-itp-micro-vol:

# bind to external network
networks:
  itp-net:
    external: true