server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: native , git     # Use native (local file system) by default. Change to 'git,vault' for production
  cloud:
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          authentication: TOKEN
          token: myroot
          kv-version: 2
          backend: secret
          profile-separator: /

        git:
          uri:  ${GL_URI}
          username: ${GL_USER}      #see-visal
          password: ${GL_TOKEN}
          default-label: main
          search-paths: "/**"  # find all folders
        native:
          search-locations:
            - file:D:\Microservices\API-Gateway\itp-config-repository
            - file:D:\Microservices\API-Gateway\itp-config-repository\{application}\
